#!/bin/sh

# go to the repo root
cd /home/grtp.co/production

# clear out all local changes
env -i git reset --hard

# wipe out node_modules and reinstall
make clean
make build

# reload configuration
service nginx reload
